### ISSUE TITLE
Images in Hikes cards

### ISSUE THREAD

**Issue by edoardocolella** [SE2-TEAM10/se2022-10-HikeTracker#16]
All hikes cards show the same picture. 
It would be nice to see different images or give the user, during creation, the possibility of being able to upload an image

**Comment by GangemiLorenzo** [comment]
Solved in https://github.com/SE2-TEAM10/se2022-10-HikeTracker/commit/fbc1e09d8392e765e5fb05acb88eaa1036943b51
